limit_req_zone $binary_remote_addr zone=one:10m rate=90r/m;

server {
    listen 80;
    server_name new-paws-beam-quietly.st.a.dcdg.xyz;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name new-paws-beam-quietly.st.a.dcdg.xyz;

    ssl_certificate /etc/letsencrypt/live/new-paws-beam-quietly.st.a.dcdg.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/new-paws-beam-quietly.st.a.dcdg.xyz/privkey.pem;

    # Optimasi SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /threads {
        limit_req zone=one burst=10 nodelay;
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}