# Definisi limitasi: 90 request per menit (90r/m)
limit_req_zone $binary_remote_addr zone=one:10m rate=90r/m;

server {
    listen 80;
    server_name 34.222.229.85;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Batasan khusus untuk /threads
	location /threads {
        limit_req zone=one burst=10 nodelay; # Tambahkan burst agar lebih fleksibel
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}