name: Continuous Deployment

on:
  push:
    branches:
      - main # CD hanya berjalan ketika ada push atau merge ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Opsional: CD baru jalan kalau job 'test' di CI sudah lulus
    # needs: test 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        # Perintah yang akan dijalankan di dalam server AWS kamu
        script: |
          cd ~/forum-api
          git pull origin main
          npm install
          npm run migrate up
          pm2 restart forum-api || pm2 start npm --name "forum-api" -- start